server:
   tomcat:
      basedir: log/tomcat  
      accesslog:
         enabled: true 
         pattern: '%h %l %u %t "%r" %s %b (%D ms)'

mybatis-plus:
  mapperLocations: classpath*:mapper/*/*.xml
  typeAliasesPackage: com.threeatom.*.entity
  configLocation: classpath:mybatis-config.xml

web:
  profile-path: /run/profile

spring:
  i18n: i18n/guidecore/master
  
  mvc:
    #表示所有的访问都经过静态资源路径
    static-path-pattern: /**
    
  profiles:
    active: dev
      
  servlet:
    multipart:
      max-file-size:  64MB
      max-request-size:  64MB


systemId: 2
videoSourceType: 视频类型:1=上传视频，2=youku，3=screenRock
youtubeApiKey: AIzaSyAls5ynrz0bDYI3l3UifbLwtSclnv7g2ao

#微信支付配置表
wx:
  payConfig:
    mchId: xxx
    mchKey: xxx
    keyPath: xxx
    notifyUrl: xxx  # 区分域名

#aliyun邮件对象配置
email:
  aliyunEmail:
    regionId: xxx
    accessKey: xxx
    secret: xxx
    accountName: xxx

#阿里云oss
oss:
   ossConfigList:
     - businessName: xx
       providerName: xx